import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload migrate:create`. The unused `payload` and `req`
    // parameters are part of the signature Payload writes, not something to
    // tidy — the file is regenerated, and editing it is editing output.
    "src/migrations/**",
  ]),
]);

export default eslintConfig;
