/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    life: Life;
    gallery: Gallery;
    'built-tools': BuiltTool;
    'used-tools': UsedTool;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    life: LifeSelect<false> | LifeSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'built-tools': BuiltToolsSelect<false> | BuiltToolsSelect<true>;
    'used-tools': UsedToolsSelect<false> | UsedToolsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    resume: Resume;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    resume: ResumeSelect<false> | ResumeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * You. There is no reason for a second row here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and video. Upload once, reference anywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and for when it fails to load. Required — the site will not ship an image without it.
   */
  alt: string;
  /**
   * Optional. Shown under the media.
   */
  caption?: string | null;
  credit?: string | null;
  /**
   * Set automatically on upload; change only if it guesses wrong.
   */
  kind?: ('image' | 'video') | null;
  /**
   * Free-form, for searching the library.
   */
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Case studies shown on /work.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * The URL. Filled in from the title; changing it later breaks existing links.
   */
  slug: string;
  /**
   * One line. Used in the index and in link previews.
   */
  summary: string;
  year: string;
  /**
   * Mono meta line, e.g. "Web / AI".
   */
  discipline: string;
  role?: string | null;
  /**
   * One technology per entry.
   */
  stack?: string[] | null;
  projectUrl?: string | null;
  githubUrl?: string | null;
  /**
   * Shows on the home page's Selected Work. Keep this to three or four.
   */
  featured?: boolean | null;
  cover: number | Media;
  /**
   * Optional short loop. When set, hovering the project in the index plays it instead of showing the cover.
   */
  previewVideo?: (number | null) | Media;
  layout?:
    | (
        | TextBlock
        | HeadingBlock
        | StatementBlock
        | SectionIntroBlock
        | QuoteBlock
        | StatsBlock
        | LocationMetaBlock
        | ImageBlock
        | WideImageBlock
        | FullBleedImageBlock
        | PhotoPairBlock
        | ImageTextBlock
        | VideoBlock
        | GalleryBlock
        | ProjectPreviewBlock
        | ToolPreviewBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock".
 */
export interface HeadingBlock {
  text: string;
  level?: ('h2' | 'h3') | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  /**
   * One line of display type per row. Keep them short.
   */
  lines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionIntroBlock".
 */
export interface SectionIntroBlock {
  index: string;
  label: string;
  lead?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quote: string;
  attribution?: string | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  items?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationMetaBlock".
 */
export interface LocationMetaBlock {
  place?: string | null;
  date?: string | null;
  /**
   * Optional, e.g. 36.5° N, 118.1° E
   */
  coordinates?: string | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locationMeta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  fit?: ('cover' | 'contain') | null;
  caption?: string | null;
  /**
   * Overrides the alt text stored on the media item. Leave empty to use that.
   */
  alt?: string | null;
  /**
   * Gentle scroll parallax. Ignored when motion is reduced.
   */
  parallax?: boolean | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WideImageBlock".
 */
export interface WideImageBlock {
  image: number | Media;
  fit?: ('cover' | 'contain') | null;
  caption?: string | null;
  /**
   * Overrides the alt text stored on the media item. Leave empty to use that.
   */
  alt?: string | null;
  /**
   * Gentle scroll parallax. Ignored when motion is reduced.
   */
  parallax?: boolean | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'wideImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullBleedImageBlock".
 */
export interface FullBleedImageBlock {
  image: number | Media;
  fit?: ('cover' | 'contain') | null;
  caption?: string | null;
  /**
   * Overrides the alt text stored on the media item. Leave empty to use that.
   */
  alt?: string | null;
  /**
   * Gentle scroll parallax. Ignored when motion is reduced.
   */
  parallax?: boolean | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullBleedImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoPairBlock".
 */
export interface PhotoPairBlock {
  left: number | Media;
  right: number | Media;
  ratio?: ('50-50' | '40-60' | '60-40' | '30-70') | null;
  fit?: ('cover' | 'contain') | null;
  /**
   * Drop the second image to create an editorial stagger.
   */
  offset?: boolean | null;
  /**
   * Optional. Shown as small mono type under the media.
   */
  caption?: string | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'photoPair';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  image: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  order?: ('image-left' | 'image-right') | null;
  ratio?: ('50-50' | '40-60' | '60-40' | '30-70') | null;
  /**
   * Optional. Shown as small mono type under the media.
   */
  caption?: string | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  video: number | Media;
  /**
   * Frame shown before playback.
   */
  poster?: (number | null) | Media;
  autoplay?: boolean | null;
  loop?: boolean | null;
  controls?: boolean | null;
  /**
   * Optional. Shown as small mono type under the media.
   */
  caption?: string | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Leave empty to show the most recent gallery photos.
   */
  photos?: (number | Gallery)[] | null;
  /**
   * Used only when no photos are chosen above.
   */
  limit?: number | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * Drag rows to set the order the ring turns through.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  _order?: string | null;
  /**
   * Pick from the Media Library, or upload here.
   */
  image: number | Media;
  title?: string | null;
  place: string;
  /**
   * e.g. "May 2026"
   */
  date: string;
  featured?: boolean | null;
  caption?: string | null;
  camera?: string | null;
  lens?: string | null;
  focalLength?: string | null;
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectPreviewBlock".
 */
export interface ProjectPreviewBlock {
  projects?: (number | Project)[] | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolPreviewBlock".
 */
export interface ToolPreviewBlock {
  tools?: (number | BuiltTool)[] | null;
  /**
   * How much of the grid this block occupies.
   */
  width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Space below this block.
   */
  spacing?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  /**
   * Auto follows the page.
   */
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * How much this block animates. Exact timings stay in the motion system.
   */
  motion?: ('none' | 'subtle' | 'default') | null;
  /**
   * Uncheck to hide without deleting.
   */
  visible?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'toolPreview';
}
/**
 * Drag to reorder. Shown under BUILT on /tools.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "built-tools".
 */
export interface BuiltTool {
  id: number;
  _order?: string | null;
  name: string;
  description: string;
  stack?: string[] | null;
  website?: string | null;
  github?: string | null;
  screenshot?: (number | null) | Media;
  video?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trips, trails and field notes shown on /life.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "life".
 */
export interface Life {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * The URL. Filled in from the title; changing it later breaks existing links.
   */
  slug: string;
  category: 'hiking' | 'travel' | 'photography' | 'outdoor' | 'personal' | 'other';
  place?: string | null;
  /**
   * e.g. "June 2026"
   */
  date?: string | null;
  description?: string | null;
  cover?: (number | null) | Media;
  /**
   * Optional. Displayed as mono metadata.
   */
  coordinates?: string | null;
  distance?: string | null;
  elevation?: string | null;
  duration?: string | null;
  difficulty?: ('easy' | 'moderate' | 'hard' | 'serious') | null;
  trail?: string | null;
  /**
   * A designed starting arrangement. All presets use the same design system.
   */
  preset?: ('editorial' | 'field-note' | 'photo-essay' | 'travel-journal' | 'minimal') | null;
  /**
   * Photo essays often read better on the dark ground.
   */
  theme?: ('light' | 'dark' | 'auto') | null;
  layout?:
    | (
        | TextBlock
        | HeadingBlock
        | StatementBlock
        | SectionIntroBlock
        | QuoteBlock
        | StatsBlock
        | LocationMetaBlock
        | ImageBlock
        | WideImageBlock
        | FullBleedImageBlock
        | PhotoPairBlock
        | ImageTextBlock
        | VideoBlock
        | GalleryBlock
        | ProjectPreviewBlock
        | ToolPreviewBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Drag to reorder within a category. Shown under USE on /tools.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used-tools".
 */
export interface UsedTool {
  id: number;
  _order?: string | null;
  name: string;
  category: 'development' | 'design' | 'hardware' | 'photography' | 'other';
  /**
   * One short line, e.g. “Editor”.
   */
  note?: string | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles for /blog. Hidden from the nav until Blog is enabled in Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * The URL. Filled in from the title; changing it later breaks existing links.
   */
  slug: string;
  description: string;
  category?: string | null;
  featured?: boolean | null;
  tags?: string[] | null;
  cover?: (number | null) | Media;
  /**
   * Set a future date to schedule: the post stays off the site until then, even once published.
   */
  publishedAt?: string | null;
  layout?:
    | (
        | TextBlock
        | HeadingBlock
        | StatementBlock
        | SectionIntroBlock
        | QuoteBlock
        | StatsBlock
        | LocationMetaBlock
        | ImageBlock
        | WideImageBlock
        | FullBleedImageBlock
        | PhotoPairBlock
        | ImageTextBlock
        | VideoBlock
        | GalleryBlock
        | ProjectPreviewBlock
        | ToolPreviewBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'life';
        value: number | Life;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'built-tools';
        value: number | BuiltTool;
      } | null)
    | ({
        relationTo: 'used-tools';
        value: number | UsedTool;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  kind?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  summary?: T;
  year?: T;
  discipline?: T;
  role?: T;
  stack?: T;
  projectUrl?: T;
  githubUrl?: T;
  featured?: T;
  cover?: T;
  previewVideo?: T;
  layout?:
    | T
    | {
        text?: T | TextBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        locationMeta?: T | LocationMetaBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        wideImage?: T | WideImageBlockSelect<T>;
        fullBleedImage?: T | FullBleedImageBlockSelect<T>;
        photoPair?: T | PhotoPairBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        projectPreview?: T | ProjectPreviewBlockSelect<T>;
        toolPreview?: T | ToolPreviewBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  body?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock_select".
 */
export interface HeadingBlockSelect<T extends boolean = true> {
  text?: T;
  level?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  lines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionIntroBlock_select".
 */
export interface SectionIntroBlockSelect<T extends boolean = true> {
  index?: T;
  label?: T;
  lead?:
    | T
    | {
        text?: T;
        id?: T;
      };
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationMetaBlock_select".
 */
export interface LocationMetaBlockSelect<T extends boolean = true> {
  place?: T;
  date?: T;
  coordinates?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  fit?: T;
  caption?: T;
  alt?: T;
  parallax?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WideImageBlock_select".
 */
export interface WideImageBlockSelect<T extends boolean = true> {
  image?: T;
  fit?: T;
  caption?: T;
  alt?: T;
  parallax?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullBleedImageBlock_select".
 */
export interface FullBleedImageBlockSelect<T extends boolean = true> {
  image?: T;
  fit?: T;
  caption?: T;
  alt?: T;
  parallax?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoPairBlock_select".
 */
export interface PhotoPairBlockSelect<T extends boolean = true> {
  left?: T;
  right?: T;
  ratio?: T;
  fit?: T;
  offset?: T;
  caption?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  image?: T;
  body?: T;
  order?: T;
  ratio?: T;
  caption?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  video?: T;
  poster?: T;
  autoplay?: T;
  loop?: T;
  controls?: T;
  caption?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  photos?: T;
  limit?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectPreviewBlock_select".
 */
export interface ProjectPreviewBlockSelect<T extends boolean = true> {
  projects?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolPreviewBlock_select".
 */
export interface ToolPreviewBlockSelect<T extends boolean = true> {
  tools?: T;
  width?: T;
  align?: T;
  spacing?: T;
  theme?: T;
  motion?: T;
  visible?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "life_select".
 */
export interface LifeSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  category?: T;
  place?: T;
  date?: T;
  description?: T;
  cover?: T;
  coordinates?: T;
  distance?: T;
  elevation?: T;
  duration?: T;
  difficulty?: T;
  trail?: T;
  preset?: T;
  theme?: T;
  layout?:
    | T
    | {
        text?: T | TextBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        locationMeta?: T | LocationMetaBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        wideImage?: T | WideImageBlockSelect<T>;
        fullBleedImage?: T | FullBleedImageBlockSelect<T>;
        photoPair?: T | PhotoPairBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        projectPreview?: T | ProjectPreviewBlockSelect<T>;
        toolPreview?: T | ToolPreviewBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  _order?: T;
  image?: T;
  title?: T;
  place?: T;
  date?: T;
  featured?: T;
  caption?: T;
  camera?: T;
  lens?: T;
  focalLength?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "built-tools_select".
 */
export interface BuiltToolsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  description?: T;
  stack?: T;
  website?: T;
  github?: T;
  screenshot?: T;
  video?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used-tools_select".
 */
export interface UsedToolsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  category?: T;
  note?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  featured?: T;
  tags?: T;
  cover?: T;
  publishedAt?: T;
  layout?:
    | T
    | {
        text?: T | TextBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        locationMeta?: T | LocationMetaBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        wideImage?: T | WideImageBlockSelect<T>;
        fullBleedImage?: T | FullBleedImageBlockSelect<T>;
        photoPair?: T | PhotoPairBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        projectPreview?: T | ProjectPreviewBlockSelect<T>;
        toolPreview?: T | ToolPreviewBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The home page: identity, hero, and the order of its sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  name: string;
  /**
   * Used in the browser tab suffix.
   */
  shortName?: string | null;
  /**
   * e.g. "Developer", "Builder", "Photographer".
   */
  roles?: string[] | null;
  basedIn?: string | null;
  year?: string | null;
  currently?: string | null;
  interests?: string[] | null;
  /**
   * The opening line, e.g. "Hi, I'm Your Name 👋". Emoji are fine.
   */
  greeting: string;
  /**
   * One line of very large type per row. Keep each under about 15 characters or it will wrap on a laptop.
   */
  headline?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        block: 'hero' | 'about' | 'work' | 'life' | 'tools' | 'elsewhere';
        visible?: boolean | null;
        motion?: ('none' | 'subtle' | 'default') | null;
        /**
         * Overrides the mono section label, e.g. “Away from the screen”. Leave empty for the default.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /about page: portrait, introduction, and the formal record. Also what the Print / Save PDF button produces.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume".
 */
export interface Resume {
  id: number;
  /**
   * The formal role line, e.g. "Developer / Interface Engineer".
   */
  title: string;
  /**
   * The photograph beside the introduction. A portrait crop reads best — it is displayed at 4:5. Left out of the printed A4, which is a document rather than a page.
   */
  portrait?: (number | null) | Media;
  /**
   * The introduction at the top of /about, set large. Two or three paragraphs; this is the part someone actually reads.
   */
  profile?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small line at the end, print included.
   */
  printNote?: string | null;
  /**
   * Drag to reorder. Newest first reads best.
   */
  experience?:
    | {
        organisation: string;
        role: string;
        /**
         * e.g. 2021
         */
        start?: string | null;
        /**
         * Blank if current
         */
        end?: string | null;
        current?: boolean | null;
        location?: string | null;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        organisation: string;
        role: string;
        /**
         * e.g. 2021
         */
        start?: string | null;
        /**
         * Blank if current
         */
        end?: string | null;
        current?: boolean | null;
        location?: string | null;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  projects?:
    | {
        name: string;
        period?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        category: string;
        items?: string[] | null;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        name: string;
        period?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  contact?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Identity, SEO, navigation and feature toggles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteUrl?: string | null;
  email: string;
  /**
   * The single accent tone. Chosen from the palette rather than picked freely, so it always sits correctly against the warm white.
   */
  accentColor?: ('clay' | 'ink' | 'moss' | 'slate' | 'ochre') | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Shown when a link to the site is shared.
   */
  seoImage?: (number | null) | Media;
  navigation?:
    | {
        route: '/about' | '/work' | '/tools' | '/life' | '/blog' | '/gallery';
        label: string;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        /**
         * Picks the icon.
         */
        platform:
          | 'px500'
          | 'behance'
          | 'bilibili'
          | 'bluesky'
          | 'buymeacoffee'
          | 'codeberg'
          | 'discord'
          | 'douyin'
          | 'dribbble'
          | 'email'
          | 'flickr'
          | 'github'
          | 'gitlab'
          | 'instagram'
          | 'linkedin'
          | 'mastodon'
          | 'patreon'
          | 'readcv'
          | 'rss'
          | 'soundcloud'
          | 'spotify'
          | 'substack'
          | 'telegram'
          | 'unsplash'
          | 'vsco'
          | 'website'
          | 'wechat'
          | 'weibo'
          | 'x'
          | 'xiaohongshu'
          | 'youtube'
          | 'zhihu';
        label: string;
        handle?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Off: /blog still works, but Writing is not shown in the navigation or on the home page. On: Writing appears in its reserved slot. No code change either way.
   */
  blogEnabled?: boolean | null;
  /**
   * The custom desktop cursor. Always off on touch and reduced motion.
   */
  cursorEnabled?: boolean | null;
  /**
   * The 3D ring on /gallery. Off falls back to the editorial grid, which is also what small screens and reduced motion get.
   */
  webglGallery?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  roles?: T;
  basedIn?: T;
  year?: T;
  currently?: T;
  interests?: T;
  greeting?: T;
  headline?:
    | T
    | {
        text?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        block?: T;
        visible?: T;
        motion?: T;
        label?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_select".
 */
export interface ResumeSelect<T extends boolean = true> {
  title?: T;
  portrait?: T;
  profile?:
    | T
    | {
        text?: T;
        id?: T;
      };
  printNote?: T;
  experience?:
    | T
    | {
        organisation?: T;
        role?: T;
        start?: T;
        end?: T;
        current?: T;
        location?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  education?:
    | T
    | {
        organisation?: T;
        role?: T;
        start?: T;
        end?: T;
        current?: T;
        location?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  projects?:
    | T
    | {
        name?: T;
        period?: T;
        body?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        category?: T;
        items?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        name?: T;
        period?: T;
        body?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  email?: T;
  accentColor?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  navigation?:
    | T
    | {
        route?: T;
        label?: T;
        visible?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        handle?: T;
        href?: T;
        id?: T;
      };
  blogEnabled?: T;
  cursorEnabled?: T;
  webglGallery?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}